# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               John Sabilla
tagline:             'Welcome to my personal site'
description:         'Software <b>Engineer</b>, Gamer, Model kit <b>Builder</b>, Tech <b>Enthusiast</b>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              John Sabilla
  url:               https://www.linkedin.com/in/john-sabilla-806b1942
  email:             johnesabilla@gmail.com

# Custom vars
version:             0.2

# Gems
gems: [jekyll-paginate]